import tensorflow as tf

FLOAT_TYPE = tf.float32

# Conv layer
CONV_WEIGHTS_RNDOM_MEAN=0.0
CONV_WEIGHTS_RNDOM_DEVIATION=0.001

CONV_BIASES_RNDOM_MEAN=0.0
CONV_BIASES_RNDOM_DEVIATION=0.001
DOES_SHOW_CONV_SUMMARY = False

# Fully-Connected layer
FC_WEIGHTS_RANDOM_MEAN=0.0
FC_WEIGHTS_RANDOM_DEVIATION=0.001

FC_BIASES_RANDOM_MEAN=0.0
FC_BIASES_RANDOM_DEVIATION=0.001
DOES_SHOW_FC_SUMMARY = False

# Regularizer
#REGULARIZER_WEIGHTS_DECAY = None
REGULARIZER_WEIGHTS_DECAY = 0.0004

# Leaky RELU
LEAKY_RELU_FACTOR=0.1

# Batch Normalization
BATCH_NORMALIZATION_MOVING_AVERAGE_DECAY_RATIO=0.997

# LSTM
LSTM_INITIALIZER = tf.contrib.layers.variance_scaling_initializer()
